baseurl = "/"
languageCode = "en-us"
title = "Potential COVID-19 cases monitoring"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 100
[[menu.main]]
    name = "About the data"
    url = "/about-data/"
[[menu.main]]
    name = "About the model"
    url = "/about-model/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/thibautjombart/nhs_pathways_monitoring"
# [[menu.main]]
#     name = "Twitter"
#     url = "https://twitter.com/rstudio"

[params]
    description = "Real-time monitoring of trend changes in potential COVID-19 cases reported through NHS pathways"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "railscasts"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

