on:
  push:
    branches:
      - main
      - master

  schedule:
    - cron:  '30 2 * * *'

name: distill

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc and other problematics
        run: |
          brew install pandoc udunits gdal geos proj

      - name: Install R packages for report building
        run: |
          pkgs <- c("remotes", "distill", "trending", "ggplot2", "DT", "cowplot", "dplyr", "tibble", "tidyr", "sf")
          install.packages(pkgs, repos = "https://cloud.r-project.org/")
          remotes::install_github("r-spatial/mapview@b96de52")
          remotes::install_github("r-spatial/leafpop@3da14fd")
          remotes::install_github("reconhub/trendbreaker@summary")
          remotes::install_github("reconhub/incidence2@a9d7be7")
        shell: Rscript {0}

      - name: Build site
        run: |
          rmarkdown::render_site(encoding = 'UTF-8')
        shell: Rscript {0}

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/*
          git commit -m "Automatic website update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true



