name: get_and_clean_data

on:
  schedule:
    - cron:  '30 1 * * *'

jobs:
  update-newbies:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: |
          R -e 'install.packages(c("rvest", "robotstxt"))'

      - name: get and clean data
        run: Rscript scripts/get_and_clean_data.R

      - name: Push update
        run: |-
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

